language: php
php:
  - 7.1
install:
  - composer install
addons:
  code_climate:
    repo_token: 245d52df6e4fcc2b25479caa4e9c80b158cf9b0ce66884427cc9f41d4013be5e
after_success:
  - vendor/bin/test-reporter
